### PR TITLE
Docs fix

### PR DESCRIPTION
**Pull request by samueldmq**
Removing double white space from docs.
The goal of this pull request is to ensure that the community is also able to use this git repository to contribute to Xalan-J.

### CODE REVIEW

**Comment by garydgregory** [comment]
```
commit -m "Fix typo reported here https://github.com/apache/xalan-j/pull/1.patch" C:/vcs/svn/apache/xalan-j/branches/xalan-j_2_7_1_maint/java/xdocs/sources/xalan/getstarted.xml
    Sending        C:/vcs/svn/apache/xalan-j/branches/xalan-j_2_7_1_maint/java/xdocs/sources/xalan/getstarted.xml
    Transmitting file data ...
    Committed revision 1594570.
```

**Comment by garydgregory** [comment]
Also fixed in trunk: Committed revision 1594575.

**Comment by samueldmq** [comment]
Hi Gary,

I guess you merged my changes manually into the SVN repository, right?

My changes could be automatically merged if you just accepted my pull request at GitHub.
I think there is a button 'Merge changes' or something similar. After this, my pull request should be automatically marked as solved.

Sincerely,
Samuel

**Comment by garydgregory** [comment]
Yes I did the changes manually.

Gary

<div>-------- Original message --------</div><div>From: Samuel de Medeiros Queiroz notifications@github.com </div><div>Date:05/14/2014  20:57  (GMT-05:00) </div><div>To: apache/xalan-j xalan-j@noreply.github.com </div><div>Cc: Gary Gregory garydgregory@gmail.com </div><div>Subject: Re: [xalan-j] Docs fix (#1) </div><div>
</div>Hi Gary,

I guess you merged my changes manually into the SVN repository, right?

My changes could be automatically merged if you just accepted my pull request at GitHub.
I think there is a button 'Merge changes' or something similar. After this, my pull request should be automatically marked as solved.

Sincerely,
Samuel

**Pull request closed without merging**
